export const DEFAULT_DAILY_RESET_TIME = '04:00';
export const ALLOW_CUSTOM_RESET_TIME = true;

export const DEFAULT_UPCOMING_LIMIT_REMINDER_SECONDS = 10;
export const MIN_UPCOMING_LIMIT_REMINDER_SECONDS = 3;
export const MAX_UPCOMING_LIMIT_REMINDER_SECONDS = 60;

export const DEFAULT_TIMER_BADGE_WIDTH_SCALE = 0.65;
export const MIN_TIMER_BADGE_WIDTH_SCALE = 0.35;
export const MAX_TIMER_BADGE_WIDTH_SCALE = 1.2;

export const DEFAULT_TIMER_BADGE_TEXT_SCALE = 1;
export const MIN_TIMER_BADGE_TEXT_SCALE = 0.7;
export const MAX_TIMER_BADGE_TEXT_SCALE = 1.8;
